version: '3'
services:
    db:
        image: "postgres:11.7"
        ports:
            - "28042:5432"
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo@odoosrv.test
            - POSTGRES_DB=postgres
        volumes:
            - /home/docker/dev-GTSI/Postgresql/Conf/postgresql.conf:/etc/postgresql/postgresql.conf
            - data-db-dev-GTSI:/var/lib/postgresql/data
        container_name: postgresql-odoo14-dev-GTSI
        restart: always
        networks:
            - PG11--dev-GTSI-network
volumes:
    data-db-dev-GTSI:
networks:
    PG11-dev-GTSI-network:

